# Generated by Django 3.2.6 on 2021-08-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_question_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
